# Generated by Django 6.1.1 on 2026-09-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STUDENTS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='section',
            field=models.CharField(default='A', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.CharField(default='Semester 1', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.CharField(default='Year 1', max_length=20),
        ),
    ]
